spring:
  application:
    name: mcp-server
          
server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
  
logging:
  level:
    com.example.mcpserver: INFO
    org.springframework.ai: INFO
    org.springframework.security: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %level - %msg%n"
  file:
    name: logs/mcp-server.log